# Import Library Yang Dibutuhkan

In [1]:
from scipy.signal import kaiserord, lfilter, firwin, freqz
import scipy as sp
import numpy as np
import heartpy as hp
import matplotlib.pyplot as plt
import pandas as pd
from scipy import signal
from numpy import savetxt
from scipy.stats import entropy
from math import log, e
import os, sys
from scipy.signal import butter, iirnotch, lfilter
from scipy.stats import norm, kurtosis
from scipy.stats import skew    
import neurokit2 as nk
from scipy.signal import find_peaks
import collections

C:\Users\helmi.ruslan\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
C:\Users\helmi.ruslan\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:167: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar'

# Interval RR + Time Domain Features

In [2]:
def find_signal_peaks(signal, minimum=0, maximum=None, freq=500):
    dist = freq/2
    r_peaks = find_peaks(signal,distance=dist,prominence=(minimum,maximum))
    return r_peaks[0].tolist()

def get_rr(r_peaks, to_sec=False,sample_rate=125):
    rr_list = []
    start_stop = []
    for i in range(len(r_peaks)-2):
        rr_list.append(r_peaks[i+1]-r_peaks[i])
        start_stop.append([r_peaks[i],r_peaks[i+1]])
    if (to_sec):
        rr_list = np.divide(rr_list,sample_rate)
    return rr_list, start_stop

# Baca Dataset, Denoising, serta Ekstrak Fitur

In [3]:
J=0 # jumlah file
directory_path = 'dataset/sehat'
for iter in range(0,2):
    for x in os.listdir(directory_path):
        if not x.lower().endswith('.csv'):
            continue
        J=J+1
    directory_path = 'dataset/pasien'
n = J #jumlah file
m = 10
FEAT = [] #bakal jadi Feature.csv
for i in range(n): 
    FEAT.append([0] * m) #mengisi dengan angka 0 semua 
directory_path = 'dataset/sehat'
J=-1
K=0
for iter in range(0,2):
    for x in os.listdir(directory_path):
        if not x.lower().endswith('.csv'):
            continue
        full_file_path = directory_path  +   '/'   + x
        J=J+1
        print ('Using file', full_file_path)
        try:
            dataraw = pd.read_csv(full_file_path,index_col='Timestamp', parse_dates=['Timestamp'])
            dataset = pd.DataFrame(dataraw['Value']) #ambil kolom value dari setiap file
        except:
            dataraw = pd.read_csv(full_file_path,index_col='timestamp', parse_dates=['timestamp'])
            dataset = pd.DataFrame(dataraw['values'])
        x1=np.array(dataset)  #ubah jadi array, namanya x1
        Dat=[]
        Dat=[0 for i in range(x1.size)] #bikin array kosong isinya 0 semua sepajang array x1
        for i in range(0,x1.size-1):
            Dat[i]=max(x1[i]) #why pakai max?
        
        
        # FIR Filter
        enhanced = hp.enhance_peaks(Dat, iterations=2)
        powerline=60
        fs = 110
        cutoff_low = 3
        nyq_rate = fs / 2.0
        width = 5.0/nyq_rate
        N, beta = kaiserord(powerline, width)
        cutoff_hz = cutoff_low
        taps = firwin(N, cutoff_hz/nyq_rate, window=('kaiser', beta))
        y_filtered = lfilter(taps, 1.0, enhanced)
            
        wd, m = hp.process(y_filtered, sample_rate=120)   
        
        # FEATURE EXTRACTION
        try:

            arr=[]
            for measure in m.keys():        
                arr.append(m[measure])
                
            peaks = find_signal_peaks(y_filtered,minimum=0.2)
            rr, rr_startstop = get_rr(peaks,to_sec=True,sample_rate=500)
            mean_ppi = np.mean(rr)
            std_ppi = np.std(rr)
            mean_signal = np.mean(y_filtered)
            std_signal = np.std(y_filtered)
            
            FEAT[J][0] = arr[0]
            FEAT[J][1] = arr[1]
            FEAT[J][2] = arr[2]
            FEAT[J][3] = arr[7]
            FEAT[J][4] = arr[12]
            FEAT[J][5] = mean_ppi
            FEAT[J][6] = std_ppi
            FEAT[J][7] = mean_signal
            FEAT[J][8] = std_signal
            FEAT[J][9] = K
            print(FEAT[J][0])

        except:
            J=J-1
        
    directory_path = 'dataset/pasien'
    K=1

Using file dataset/sehat/sehat1-nizar.csv
104.19681620839364
Using file dataset/sehat/sehat10-bagas.csv
90.8777969018933
Using file dataset/sehat/sehat11-fian.csv
107.06319702602231
Using file dataset/sehat/sehat12-faizalaryo.csv
112.37458193979933
Using file dataset/sehat/sehat13-dani.csv
113.68421052631578
Using file dataset/sehat/sehat14 -pradana.csv
105.993690851735
Using file dataset/sehat/sehat15-rifkun.csv


C:\Users\helmi.ruslan\Anaconda3\lib\site-packages\numpy\ma\core.py:5244: RuntimeWarning: Mean of empty slice.
  result = super().mean(axis=axis, dtype=dtype, **kwargs)[()]
C:\Users\helmi.ruslan\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3724: RuntimeWarning: Degrees of freedom <= 0 for slice
  **kwargs)


78.68852459016394
Using file dataset/sehat/sehat16-Nirel.csv
86.4345738295318
Using file dataset/sehat/sehat17-Sesil.csv
101.75438596491229
Using file dataset/sehat/sehat18-Almer.csv
101.75438596491229
Using file dataset/sehat/sehat19-Aqil.csv
95.57522123893806
Using file dataset/sehat/sehat2-bintang.csv
118.49901250822909
Using file dataset/sehat/sehat20-thomi.csv
116.19596541786744
Using file dataset/sehat/sehat21-fuad.csv
107.73834972210346
Using file dataset/sehat/sehat22 - mahavira.csv
69.97840172786177
Using file dataset/sehat/sehat23 - tati.csv
83.35745296671492
Using file dataset/sehat/sehat24-Alvyn.csv
124.4060475161987
Using file dataset/sehat/sehat25-Ivan.csv
108.85529157667388
Using file dataset/sehat/sehat26-habibi.csv
104.66717674062743
Using file dataset/sehat/sehat27-faris.csv
90.6474820143885
Using file dataset/sehat/sehat28-guslal.csv
69.80609418282549
Using file dataset/sehat/sehat29-teddy.csv
111.47540983606557
Using file dataset/sehat/sehat3-sena.csv
107.8039927404

# Export hasil ekstraksi fitur

In [4]:
import csv
#bikin csv
with open("Features(sk2).csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(FEAT)



# Baca Dataset hasil ekstraksi

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# import sklearn

dataset = pd.read_csv('Features(sk2).csv', names=['bpm','ibi','sdnn', 'hr_mad','breathingrate','Mean PPI', 'Std PPI', 'Mean Signal','Std signal','label'])

# data_uji = pd.read_csv('Featuree2.csv', names=['bpm', 'ibi', 'sdnn','sdsd','rmssd','pnn20','pnn50','hr_mad','sd1','sd2','s','sd1/sd2','breathingrate'])
label = dataset['label']
dataset = dataset.drop(columns='label')


In [6]:
dataset.isnull().sum()


bpm              0
ibi              0
sdnn             0
hr_mad           0
breathingrate    4
Mean PPI         0
Std PPI          0
Mean Signal      0
Std signal       0
dtype: int64

In [7]:
dataset['breathingrate']=dataset['breathingrate'].fillna(dataset['breathingrate'].mean())


# Tahapan Klasifikasi

In [8]:
# MACHINE LEARNING
# SPLIT DATA 70% TRAIN, 30% DATA TEST
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score
from numpy import random

x = random.randint(100)

# 2
X_train, X_test, y_train, y_test = train_test_split(dataset, label, test_size = 0.30,random_state=2)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


print('DATA TRAIN')
print(X_train.shape)
print('LABEL TRAIN')
print(y_train.shape)
print('DATA TEST')
print(X_test.shape)
print('LABEL TEST')
print(y_test.shape)


# Import the classifier from sklearn
from sklearn.tree import DecisionTreeClassifier

# TODO: Define the classifier, and fit it to the data
model = DecisionTreeClassifier(random_state=20)
model.fit(X_train, y_train) 
y_test_pred = model.predict(X_test)

print('HASIL PREDIKSI')
print(y_test_pred)
y_train_pred = model.predict(X_train)

from sklearn.metrics import accuracy_score
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)
cm2 = confusion_matrix(y_test, y_test_pred)

print('The training accuracy is', train_accuracy)
print('The test accuracy is', test_accuracy)


from sklearn import svm

clf = svm.SVC()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print('HASIL PREDIKSI')
print(y_pred)

cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test,y_pred)
print ("Akurasi SVM", ac*100,' %') 

DATA TRAIN
(40, 9)
LABEL TRAIN
(40,)
DATA TEST
(18, 9)
LABEL TEST
(18,)
HASIL PREDIKSI
[1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 1]
The training accuracy is 1.0
The test accuracy is 0.8888888888888888
HASIL PREDIKSI
[0 0 1 0 1 0 0 1 1 0 0 1 0 0 0 0 1 0]
Akurasi SVM 61.111111111111114  %


C:\Users\helmi.ruslan\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)


# Hasil Sensitifiti, Spesifisiti

In [9]:
TP = cm2[1][1]

TN = cm2[0][0]
FP = cm2[0][1]
FN = cm2[1][0]
# calculate accuracy
conf_accuracy = (float (TP+TN) / float(TP + TN + FP + FN))

# calculate mis-classification
conf_misclassification = 1- conf_accuracy

# calculate the sensitivity
conf_sensitivity = (TP / float(TP + FN))
# calculate the specificity
conf_specificity = (TN / float(TN + FP))

# calculate precision
conf_precision = (TN / float(TN + FP))
print(conf_specificity)
print(conf_sensitivity)
print(conf_specificity)

0.7777777777777778
1.0
0.7777777777777778


# Interval RR + HRV Features

In [10]:
def shannon_entropy(data):
    bases = collections.Counter([tmp_base for tmp_base in data])
    # define distribution
    dist = [x/sum(bases.values()) for x in bases.values()]
 
    # use scipy to calculate entropy
    entropy_value = entropy(dist, base=2)
 
    return entropy_value



# Baca Dataset, Denoising, Serta Ekstraksi Ciri

In [11]:
J=0 # jumlah file
directory_path = 'dataset/sehat'
for iter in range(0,2):
    for x in os.listdir(directory_path):
        if not x.lower().endswith('.csv'):
            continue
        J=J+1
    directory_path = 'dataset/pasien'
n = J #jumlah file
m = 13
FEAT = [] #bakal jadi Feature.csv
for i in range(n): 
    FEAT.append([0] * m) #mengisi dengan angka 0 semua 
directory_path = 'dataset/sehat'
J=-1
K=0
for iter in range(0,2):
    for x in os.listdir(directory_path):
        if not x.lower().endswith('.csv'):
            continue
        full_file_path = directory_path  +   '/'   + x
        J=J+1
        print ('Using file', full_file_path)
        try:
            dataraw = pd.read_csv(full_file_path,index_col='Timestamp', parse_dates=['Timestamp'])
            dataset = pd.DataFrame(dataraw['Value']) #ambil kolom value dari setiap file
        except:
            dataraw = pd.read_csv(full_file_path,index_col='timestamp', parse_dates=['timestamp'])
            dataset = pd.DataFrame(dataraw['values'])
        x1=np.array(dataset)  #ubah jadi array, namanya x1
        Dat=[]
        Dat=[0 for i in range(x1.size)] #bikin array kosong isinya 0 semua sepajang array x1
        for i in range(0,x1.size-1):
            Dat[i]=max(x1[i]) #why pakai max?
        
        
        # FIR Filter
        enhanced = hp.enhance_peaks(Dat, iterations=2)
        powerline=60
        fs = 110
        cutoff_low = 3
        nyq_rate = fs / 2.0
        width = 5.0/nyq_rate
        N, beta = kaiserord(powerline, width)
        cutoff_hz = cutoff_low
        taps = firwin(N, cutoff_hz/nyq_rate, window=('kaiser', beta))
        y_filtered = lfilter(taps, 1.0, enhanced)
            
        wd, m = hp.process(y_filtered, sample_rate=120)   
        
        # FEATURE EXTRACTION
        try:

            arr=[]
            for measure in m.keys():        
                arr.append(m[measure])
            # Shannon entropy
            ESH=shannon_entropy(y_filtered)
            FEAT[J][0] = ESH
            

            # MAD
            series = pd.Series(y_filtered)
            MAD = series.mad()
            # Kurtosis
            KURT = kurtosis(y_filtered)
            # Skewness
            SKEW = skew(y_filtered)
           
            #vlf,lf,hf
            info = nk.ppg_findpeaks(y_filtered)
            peak = info["PPG_Peaks"]
            hrv_freq = nk.hrv_frequency(peak, sampling_rate=39, normalize=True)
            VLF=hrv_freq['HRV_VLF'].values[0]
            LF=hrv_freq['HRV_LF'].values[0]
            HF=hrv_freq['HRV_HF'].values[0]
            
            FEAT[J][0] = arr[0]
            FEAT[J][1] = arr[1]
            FEAT[J][2] = arr[2]
            FEAT[J][3] = arr[7]
            FEAT[J][4] = arr[12]
            FEAT[J][5] = ESH
            FEAT[J][6] = MAD
            FEAT[J][7] = KURT
            FEAT[J][8] = SKEW
            FEAT[J][9] = VLF
            FEAT[J][10] = LF
            FEAT[J][11] = HF
            FEAT[J][12] = K

        except:
            J=J-1
        
    directory_path = 'dataset/pasien'
    K=1

Using file dataset/sehat/sehat1-nizar.csv
Using file dataset/sehat/sehat10-bagas.csv
Using file dataset/sehat/sehat11-fian.csv
Using file dataset/sehat/sehat12-faizalaryo.csv
Using file dataset/sehat/sehat13-dani.csv
Using file dataset/sehat/sehat14 -pradana.csv
Using file dataset/sehat/sehat15-rifkun.csv


C:\Users\helmi.ruslan\Anaconda3\lib\site-packages\numpy\ma\core.py:5244: RuntimeWarning: Mean of empty slice.
  result = super().mean(axis=axis, dtype=dtype, **kwargs)[()]
C:\Users\helmi.ruslan\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3724: RuntimeWarning: Degrees of freedom <= 0 for slice
  **kwargs)


Using file dataset/sehat/sehat16-Nirel.csv
Using file dataset/sehat/sehat17-Sesil.csv
Using file dataset/sehat/sehat18-Almer.csv
Using file dataset/sehat/sehat19-Aqil.csv
Using file dataset/sehat/sehat2-bintang.csv
Using file dataset/sehat/sehat20-thomi.csv
Using file dataset/sehat/sehat21-fuad.csv
Using file dataset/sehat/sehat22 - mahavira.csv
Using file dataset/sehat/sehat23 - tati.csv
Using file dataset/sehat/sehat24-Alvyn.csv
Using file dataset/sehat/sehat25-Ivan.csv
Using file dataset/sehat/sehat26-habibi.csv
Using file dataset/sehat/sehat27-faris.csv
Using file dataset/sehat/sehat28-guslal.csv
Using file dataset/sehat/sehat29-teddy.csv
Using file dataset/sehat/sehat3-sena.csv
Using file dataset/sehat/sehat30-bayu.csv
Using file dataset/sehat/sehat4-safril.csv
Using file dataset/sehat/sehat5-hisyam.csv
Using file dataset/sehat/sehat6-niko.csv
Using file dataset/sehat/sehat7-aflah.csv
Using file dataset/sehat/sehat8-wahyu.csv
Using file dataset/sehat/sehat9-eric.csv
Using file dat

# Eksport Hasil Ekstraksi

In [12]:
import csv
#bikin csv
with open("Features(sk22).csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(FEAT)



# Baca Dataset hasil ekstraksi fitur

In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# import sklearn

dataset = pd.read_csv('Features(sk22).csv', names=['bpm','ibi','sdnn', 'hr_mad','breathingrate','ESH', 'MAD', 'KURT','SKEW','VLF','LF','HF','label'])

# data_uji = pd.read_csv('Featuree2.csv', names=['bpm', 'ibi', 'sdnn','sdsd','rmssd','pnn20','pnn50','hr_mad','sd1','sd2','s','sd1/sd2','breathingrate'])
label = dataset['label']
dataset = dataset.drop(columns='label')


In [14]:
dataset.isnull().sum()

bpm              0
ibi              0
sdnn             0
hr_mad           0
breathingrate    4
ESH              0
MAD              0
KURT             0
SKEW             0
VLF              2
LF               0
HF               0
dtype: int64

In [15]:
dataset['breathingrate']=dataset['breathingrate'].fillna(dataset['breathingrate'].mean())
dataset['VLF'] = dataset['VLF'].fillna(0)


# Tahapan Klasifikasi

In [16]:
# MACHINE LEARNING
# SPLIT DATA 80% TRAIN, 20% DATA TEST
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score
from numpy import random

X_train, X_test, y_train, y_test = train_test_split(dataset, label, test_size = 0.30,random_state=32)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


print('DATA TRAIN')
print(X_train.shape)
print('LABEL TRAIN')
print(y_train.shape)
print('DATA TEST')
print(X_test.shape)
print('LABEL TEST')
print(y_test.shape)


# Import the classifier from sklearn
from sklearn.tree import DecisionTreeClassifier

# TODO: Define the classifier, and fit it to the data
model = DecisionTreeClassifier(random_state=20)
model.fit(X_train, y_train) 
y_test_pred = model.predict(X_test)

print('HASIL PREDIKSI')
print(y_test_pred)
y_train_pred = model.predict(X_train)

from sklearn.metrics import accuracy_score
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)
cm2 = confusion_matrix(y_test, y_test_pred)

print('The training accuracy is', train_accuracy)
print('The test accuracy is', test_accuracy)


from sklearn import svm

clf = svm.SVC()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print('HASIL PREDIKSI')
print(y_pred)

cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test,y_pred)
print ("Akurasi SVM", ac*100,' %') 

DATA TRAIN
(40, 12)
LABEL TRAIN
(40,)
DATA TEST
(18, 12)
LABEL TEST
(18,)
HASIL PREDIKSI
[1 1 0 0 0 1 1 1 1 0 1 1 0 0 1 1 1 1]
The training accuracy is 1.0
The test accuracy is 0.9444444444444444
HASIL PREDIKSI
[0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0]
Akurasi SVM 55.55555555555556  %


C:\Users\helmi.ruslan\Anaconda3\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)


# Hasil Sensitifiti, spesifisiti

In [17]:
TP = cm2[1][1]

TN = cm2[0][0]
FP = cm2[0][1]
FN = cm2[1][0]
# calculate accuracy
conf_accuracy = (float (TP+TN) / float(TP + TN + FP + FN))

# calculate mis-classification
conf_misclassification = 1- conf_accuracy

# calculate the sensitivity
conf_sensitivity = (TP / float(TP + FN))
# calculate the specificity
conf_specificity = (TN / float(TN + FP))

# calculate precision
conf_precision = (TN / float(TN + FP))
print(conf_specificity)
print(conf_sensitivity)
print(conf_specificity)

0.8571428571428571
1.0
0.8571428571428571
